module.exports = require('express')()
.use('/user',require('./routers/userRouter'))
.use('/apply',require('./routers/applyRouter'))
.use('/news',require('./routers/newsRouter'))
.use('/webdata',require('./routers/webRouter'))
.use('/admin',require('./routers/adminRouter'))
.use('/stipendiat',require('./routers/stipendiyatR'))
.use('/sitesettings',require('./routers/siteActionR'))
.use('/application',require('./routers/stpR'))
.use('/period',require('./routers/periodR'))