module.exports = require('express')()
.use('/user',require('./routers/userRouter'))
.use('/apply',require('./routers/applyRouter'))
.use('/news',require('./routers/newsRouter'))
.use('/webdata',require('./routers/webRouter'))
.use('/chiodata',require('./routers/chioRouter'))