module.exports= require('mongoose').model('ChioBarber',{
    name:String,
    photo:String,
    phone:String,
    orders:Array,
    date:String,
    password:String,
    table:String,
    rank:String,
    access_token:String,
    editor:{
        type:Boolean,
        default:false
    },
    isWorking:{
        type:Boolean,
        default:true
    },
    workStart:{
        type:Number,
        default:9
    },
    workEnd:{
        type:Number,
        default:21
    }
})