const applicationController = require('../controllers/adminConroller')
const userWare = require('../middlewares/adminWare')
module.exports = require('express')()
.post('/add', applicationController.add)
.get('/getall', applicationController.getall)
.get('/check',userWare, applicationController.check)
.post("/signin", applicationController.signin)
.get("/leave",userWare, applicationController.leave)
.put("/edit",userWare, applicationController.edit)
.delete("/delete/:id",applicationController.delete)
