const adminController = require('../controllers/adminConroller')
const adminWare = require('../middlewares/adminWare')
module.exports = require('express')()
.post('/add', adminWare, adminController.add)
.get('/getall', adminWare, adminController.getall)
.get('/check', adminWare, adminController.check)
.post("/signin", adminController.signin)
.get("/leave", adminWare, adminController.leave)
.put("/edit", adminWare, adminController.edit)
.delete("/delete/:id", adminWare, adminController.delete)
.get("/getone/:id", adminWare, adminController.getone)
