module.exports=require('express')()
.post('/add',require('../controllers/applyController').add)
.post('/resend',require('../controllers/applyController').resend)
.put('/updatestatus',require('../controllers/applyController').updateStatus)
.get('/getall', require('../controllers/applyController').getAll)
.delete('/deleteall', require('../controllers/applyController').deleteAll)
.delete('/deleteone/:id', require('../controllers/applyController').deleteOne)
.get('/:usernameId',require('../controllers/applyController').getOne)
.put('/updateIsWinner',require('../controllers/applyController').updateWinner)