module.exports=require('express')()
.post('/add',require('../controllers/applyController').add)
.put('/updatestatus',require('../controllers/applyController').updateStatus)
.get('/getall', require('../controllers/applyController').getAll)
.delete('/deleteall', require('../controllers/applyController').deleteAll)
