const applicationController = require('../controllers/applicationController')
const adminWare = require('../middlewares/adminWare')
const userWare = require('../middlewares/userWare')
module.exports = require('express')()
.post('/add', applicationController.add)
.post('/addStp', applicationController.addStp)
.get('/getall',adminWare, applicationController.getAll)
.get('/check',userWare, applicationController.check)
.post("/signin", applicationController.signin)
.get("/leave",userWare, applicationController.leave)
