const applicationController = require('../controllers/applicationController')
const userWare = require('../middlewares/userWare')
module.exports = require('express')()
.post('/add', applicationController.add)
.get('/getall', applicationController.getAll)
.get('/check',userWare, applicationController.check)
.post("/signin", applicationController.signin)
.get("/leave",userWare, applicationController.leave)
